version: '3.8'
services:
  postgres_db_container:
    image: postgres:latest
    container_name: "postgres_db_container"
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_db_data_container:/var/lib/postgresql/data
volumes:
  postgres_db_data_container: